#
# @dockerfile Copyright (c) 2023 Jalasoft.
# 2643 Av Melchor Perez de Olguin, Colquiri Sud, Cochabamba, Bolivia.
# All rights reserved.
#
# This software is the confidential and proprietary information of
# Jalasoft, ("Confidential Information"). You shall not
# disclose such Confidential Information and shall use it only in
# accordance with the terms of the license agreement you entered into
# with Jalasoft.
#

FROM danisku/convbase:1.02

WORKDIR /app
COPY . .

RUN pip install -r requirements.txt --no-cache

CMD ["python3", "CONVERTER/src/com/jalasoft/converter/main.py", "ffmpeg", "libmagickwand", "tesseract"]
